version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./
      dockerfile: rabbitmq.Dockerfile
    networks:
      - mukgo_internal
    restart: on-failure
    env_file: ./build_config/rabbitmq.env
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - TZ=Asia/Seoul

  api_server:
    container_name: api_server
    build:
      context: ./
      dockerfile: api_server.Dockerfile
    networks:
      - mukgo_internal
    depends_on:
      - rabbitmq
    restart: on-failure
    ports:
      - '7777:7777'
    environment:
      - TZ=Asia/Seoul

  log_server:
    container_name: log_server
    build:
      context: ./
      dockerfile: log_server.Dockerfile
    networks:
      - mukgo_internal
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - TZ=Asia/Seoul


networks:
  mukgo_internal:
    driver: bridge
