version: '3.8'

services:
  rabbitmq:
    build:
      context: ./build/rabbitmq
      dockerfile: Dockerfile
    env_file: ./build/rabbitmq/.env
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
