version: '3.8'

services:
  rabbitmq:
    build:
      context: ./
      dockerfile: rabbitmq.Dockerfile
    env_file: ./build_config/rabbitmq.env
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
