version: '3.8'

services:
  rabbitmq:
    build:
      context: ./
      dockerfile: rabbitmq.Dockerfile
    networks:
      - server_network
    env_file: ./build_config/rabbitmq.env
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  api-server:
    build:
      context: ./
      dockerfile: api_server.Dockerfile
    networks:
      - server_network
    depends_on:
      - rabbitmq
    restart: on-failure
    container_name: api-server
    ports:
      - '7777:7777'
    command: ["-mqaddr", "rabbitmq:5672"]

networks:
  server_network:
    driver: bridge
